/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.DishInfoController;
import controller.MenuBarController;
import controller.PMenuController;
import javax.swing.JFrame;
import controller.ManipulationWithDishInfo;
import controller.ManipulationWithMenu;
import javax.swing.ImageIcon;

/**
 *
 * @author dell
 */
public class DishInfo extends JFrame{
    InterfaceView interfaceView;
    ManipulationWithDishInfo manipulationWithDishInfo;
    DishInfoController dishInfoController;
    /**
     * Creates new form DishInfo
     */
    public DishInfo(InterfaceView interfaceView) {
        ImageIcon icon = new ImageIcon("src//ProGastroImage//frameicon.png");
        this.setIconImage(icon.getImage());
        this.interfaceView = interfaceView;
        this.manipulationWithDishInfo = new ManipulationWithDishInfo(this, interfaceView);
        dishInfoController = new DishInfoController(this, manipulationWithDishInfo);
        initComponents();
        addListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fDishInfo = new javax.swing.JFrame();
        pDishInfo = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        tfPrice = new javax.swing.JTextField();
        tfName = new javax.swing.JTextField();
        spDescription = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        btnFix = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        lbImage = new javax.swing.JLabel();
        btnChoose = new javax.swing.JButton();

        javax.swing.GroupLayout fDishInfoLayout = new javax.swing.GroupLayout(fDishInfo.getContentPane());
        fDishInfo.getContentPane().setLayout(fDishInfoLayout);
        fDishInfoLayout.setHorizontalGroup(
            fDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        fDishInfoLayout.setVerticalGroup(
            fDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Infomation");
        setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 12)); // NOI18N
        setName("InformationFrame"); // NOI18N

        pDishInfo.setBackground(new java.awt.Color(204, 255, 255));
        pDishInfo.setForeground(new java.awt.Color(0, 153, 153));
        pDishInfo.setPreferredSize(new java.awt.Dimension(210, 468));

        lbName.setBackground(new java.awt.Color(0, 153, 153));
        lbName.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 18)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("Description");
        lbName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbName.setOpaque(true);

        lbPrice.setBackground(new java.awt.Color(0, 153, 153));
        lbPrice.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 18)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(255, 255, 255));
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrice.setText("Name");
        lbPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbPrice.setOpaque(true);

        lbDescription.setBackground(new java.awt.Color(0, 153, 153));
        lbDescription.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 18)); // NOI18N
        lbDescription.setForeground(new java.awt.Color(255, 255, 255));
        lbDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescription.setText("Price");
        lbDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbDescription.setOpaque(true);

        taDescription.setColumns(20);
        taDescription.setRows(5);
        spDescription.setViewportView(taDescription);

        btnFix.setBackground(new java.awt.Color(0, 153, 153));
        btnFix.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnFix.setForeground(new java.awt.Color(255, 255, 255));
        btnFix.setText("Edit");

        btnRemove.setBackground(new java.awt.Color(0, 153, 153));
        btnRemove.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.setActionCommand("btnRemove");

        lbImage.setBackground(new java.awt.Color(153, 255, 255));

        btnChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProGastroImage/icon ảnh-01.png"))); // NOI18N
        btnChoose.setActionCommand("btnChoose");

        javax.swing.GroupLayout pDishInfoLayout = new javax.swing.GroupLayout(pDishInfo);
        pDishInfo.setLayout(pDishInfoLayout);
        pDishInfoLayout.setHorizontalGroup(
            pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pDishInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFix, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addGroup(pDishInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pDishInfoLayout.createSequentialGroup()
                            .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfName))
                        .addGroup(pDishInfoLayout.createSequentialGroup()
                            .addComponent(lbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pDishInfoLayout.createSequentialGroup()
                            .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pDishInfoLayout.createSequentialGroup()
                        .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pDishInfoLayout.setVerticalGroup(
            pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pDishInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbImage, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChoose))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(pDishInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFix, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDishInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pDishInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    public void addListener()
    {
        btnFix.addActionListener(dishInfoController);
        btnChoose.addActionListener(dishInfoController);
        btnRemove.addActionListener(dishInfoController);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnChoose;
    public javax.swing.JButton btnFix;
    public javax.swing.JButton btnRemove;
    private javax.swing.JFrame fDishInfo;
    public javax.swing.JLabel lbDescription;
    public javax.swing.JLabel lbImage;
    public javax.swing.JLabel lbName;
    public javax.swing.JLabel lbPrice;
    public javax.swing.JPanel pDishInfo;
    private javax.swing.JScrollPane spDescription;
    public javax.swing.JTextArea taDescription;
    public javax.swing.JTextField tfName;
    public javax.swing.JTextField tfPrice;
    // End of variables declaration//GEN-END:variables
}
