/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.PMenuController;
import controller.MenuBarController;
import model.ManipulationWithMenu;

/**
 *
 * @author dell
 */
public class InterfaceView extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceView
     */
    
    MenuBarController menuBarController = new MenuBarController(this);
    ManipulationWithMenu manipulationWithMenu = new ManipulationWithMenu(this);
    PMenuController pMenuController = new PMenuController(this, manipulationWithMenu);
    
    
    public InterfaceView() {
        System.out.println("init RestaurantMangagerView");
        initComponents();
        pManipulation.setVisible(false);
        addController();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pMenu = new javax.swing.JPanel();
        pManipulation = new javax.swing.JPanel();
        btnName = new javax.swing.JButton();
        tfNameInMenu = new javax.swing.JTextField();
        btnPriceOfMenu = new javax.swing.JButton();
        tfPriceOfMenu = new javax.swing.JTextField();
        scpOfDescription = new javax.swing.JScrollPane();
        taDescriptionInMenu = new javax.swing.JTextArea();
        btnDescriptionOfMenu = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        lbArrowDown = new javax.swing.JLabel();
        lbArrow = new javax.swing.JLabel();
        scpDishes = new javax.swing.JScrollPane();
        pOfScp = new javax.swing.JPanel();
        pTables = new javax.swing.JPanel();
        pOnTheTable = new javax.swing.JPanel();
        scpDishesOnTable = new javax.swing.JScrollPane();
        tblAllDishes = new javax.swing.JTable();
        menuBar = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        menuTables = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ProGastro");
        setName("frame"); // NOI18N
        setResizable(false);

        pManipulation.setPreferredSize(new java.awt.Dimension(652, 0));

        btnName.setText("Name of dish");
        btnName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNameActionPerformed(evt);
            }
        });

        tfNameInMenu.setBackground(new java.awt.Color(255, 255, 255));
        tfNameInMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNameInMenuActionPerformed(evt);
            }
        });

        btnPriceOfMenu.setText("Price of dish");
        btnPriceOfMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPriceOfMenuActionPerformed(evt);
            }
        });

        tfPriceOfMenu.setBackground(new java.awt.Color(255, 255, 255));

        taDescriptionInMenu.setBackground(new java.awt.Color(255, 255, 255));
        taDescriptionInMenu.setColumns(20);
        taDescriptionInMenu.setRows(5);
        scpOfDescription.setViewportView(taDescriptionInMenu);

        btnDescriptionOfMenu.setText("Description");
        btnDescriptionOfMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescriptionOfMenuActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");

        btnSave.setText("Save");

        lbArrowDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProGastroImage/arrow_13475987 - Copy.png"))); // NOI18N

        javax.swing.GroupLayout pManipulationLayout = new javax.swing.GroupLayout(pManipulation);
        pManipulation.setLayout(pManipulationLayout);
        pManipulationLayout.setHorizontalGroup(
            pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pManipulationLayout.createSequentialGroup()
                .addContainerGap(202, Short.MAX_VALUE)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184)
                .addComponent(lbArrowDown)
                .addContainerGap())
            .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pManipulationLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnDescriptionOfMenu)
                        .addGroup(pManipulationLayout.createSequentialGroup()
                            .addComponent(btnName, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfNameInMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(18, 18, 18)
                    .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scpOfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pManipulationLayout.createSequentialGroup()
                            .addComponent(btnPriceOfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(tfPriceOfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(8, Short.MAX_VALUE)))
        );
        pManipulationLayout.setVerticalGroup(
            pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pManipulationLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbArrowDown))
                .addContainerGap())
            .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pManipulationLayout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfPriceOfMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                            .addComponent(btnPriceOfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNameInMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pManipulationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scpOfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(btnDescriptionOfMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(75, 75, 75)))
        );

        lbArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ProGastroImage/arrow_13475987.png"))); // NOI18N

        scpDishes.setBackground(new java.awt.Color(0, 204, 204));

        pOfScp.setPreferredSize(new java.awt.Dimension(645, 430));
        pOfScp.setLayout(new java.awt.GridLayout(5, 2));
        scpDishes.setViewportView(pOfScp);

        javax.swing.GroupLayout pMenuLayout = new javax.swing.GroupLayout(pMenu);
        pMenu.setLayout(pMenuLayout);
        pMenuLayout.setHorizontalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
            .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pManipulation, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
            .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pMenuLayout.createSequentialGroup()
                    .addGap(309, 309, 309)
                    .addComponent(lbArrow)
                    .addContainerGap(309, Short.MAX_VALUE)))
            .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pMenuLayout.createSequentialGroup()
                    .addGap(3, 3, 3)
                    .addComponent(scpDishes, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .addGap(3, 3, 3)))
        );
        pMenuLayout.setVerticalGroup(
            pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
            .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLayout.createSequentialGroup()
                    .addGap(0, 275, Short.MAX_VALUE)
                    .addComponent(pManipulation, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pMenuLayout.createSequentialGroup()
                    .addContainerGap(447, Short.MAX_VALUE)
                    .addComponent(lbArrow)
                    .addContainerGap()))
            .addGroup(pMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pMenuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(scpDishes, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );

        tblAllDishes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        scpDishesOnTable.setViewportView(tblAllDishes);

        javax.swing.GroupLayout pOnTheTableLayout = new javax.swing.GroupLayout(pOnTheTable);
        pOnTheTable.setLayout(pOnTheTableLayout);
        pOnTheTableLayout.setHorizontalGroup(
            pOnTheTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOnTheTableLayout.createSequentialGroup()
                .addComponent(scpDishesOnTable, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
                .addContainerGap())
        );
        pOnTheTableLayout.setVerticalGroup(
            pOnTheTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOnTheTableLayout.createSequentialGroup()
                .addComponent(scpDishesOnTable, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 164, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pTablesLayout = new javax.swing.GroupLayout(pTables);
        pTables.setLayout(pTablesLayout);
        pTablesLayout.setHorizontalGroup(
            pTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pOnTheTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pTablesLayout.setVerticalGroup(
            pTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTablesLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(pOnTheTable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        menu.setText("Menu");
        menuBar.add(menu);

        menuTables.setText("Tables");
        menuBar.add(menuTables);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pTables, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(pTables, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pTables.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNameActionPerformed

    private void btnPriceOfMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPriceOfMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPriceOfMenuActionPerformed

    private void btnDescriptionOfMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescriptionOfMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDescriptionOfMenuActionPerformed

    private void tfNameInMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNameInMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNameInMenuActionPerformed

    
        
    
    /**
     * @param args the command line arguments
     */
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnDescriptionOfMenu;
    public javax.swing.JButton btnName;
    public javax.swing.JButton btnPriceOfMenu;
    public javax.swing.JButton btnSave;
    public javax.swing.JLabel lbArrow;
    public javax.swing.JLabel lbArrowDown;
    public javax.swing.JMenu menu;
    public javax.swing.JMenuBar menuBar;
    public javax.swing.JMenu menuTables;
    public javax.swing.JPanel pManipulation;
    public javax.swing.JPanel pMenu;
    public javax.swing.JPanel pOfScp;
    public javax.swing.JPanel pOnTheTable;
    public javax.swing.JPanel pTables;
    public javax.swing.JScrollPane scpDishes;
    public javax.swing.JScrollPane scpDishesOnTable;
    public javax.swing.JScrollPane scpOfDescription;
    public javax.swing.JTextArea taDescriptionInMenu;
    public javax.swing.JTable tblAllDishes;
    public javax.swing.JTextField tfNameInMenu;
    public javax.swing.JTextField tfPriceOfMenu;
    // End of variables declaration//GEN-END:variables

    public void addController(){
        menu.addMouseListener(menuBarController);
        menuTables.addMouseListener(menuBarController);
        lbArrow.addMouseListener(menuBarController);
        lbArrowDown.addMouseListener(menuBarController);
        btnAdd.addActionListener(pMenuController);
        btnSave.addActionListener(pMenuController);
    }

    public void turnOnPDishInfo() {
        pTables.setVisible(false);
    }

    
}
