/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Model.Dish;
import controller.PTableController;
import controller.TableInfoController;
import java.util.Set;
import javax.swing.table.DefaultTableModel;
import model.BtnTable;
import controller.ManipulationWithTable;
import javax.swing.ImageIcon;
import model.Table;

/**
 *
 * @author dell
 */
public class TableInfo extends javax.swing.JFrame {

    /**
     * Creates new form TableInfo
     */
    TableInfoController tableInfoController = new TableInfoController(this);
    public TableInfo() {
        ImageIcon icon = new ImageIcon("src//ProGastroImage//frameicon.png");
        this.setIconImage(icon.getImage());
        initComponents();
        initListener();
        this.table.getTableHeader().setDefaultRenderer(new CustomHeaderRenderer());
    }

    
    public void initListener(){
        this.btnRemove.addActionListener(tableInfoController);
        this.btnSave.addActionListener(tableInfoController);
        this.btnFindDish.addActionListener(tableInfoController);
        this.btnAdd.addActionListener(tableInfoController);
        this.btnEdit.addActionListener(tableInfoController);
        this.btnExport.addActionListener(tableInfoController);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pTableInfo = new javax.swing.JPanel();
        btnRemove = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lbSum = new javax.swing.JLabel();
        lbSumShow = new javax.swing.JLabel();
        pAdd = new javax.swing.JPanel();
        tfNameShow = new javax.swing.JTextField();
        tfPriceShow = new javax.swing.JTextField();
        tfQuantityShow = new javax.swing.JTextField();
        scpOfDescription = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        lbName = new javax.swing.JLabel();
        lbPrice = new javax.swing.JLabel();
        lbDescription = new javax.swing.JLabel();
        lbQuantity = new javax.swing.JLabel();
        scpOfTable = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        tfFindDish = new javax.swing.JTextField();
        btnFindDish = new javax.swing.JButton();
        scpRcm = new javax.swing.JScrollPane();
        pRcmDish = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Table Info");
        setBackground(new java.awt.Color(204, 255, 255));

        pTableInfo.setBackground(new java.awt.Color(204, 255, 255));

        btnRemove.setBackground(new java.awt.Color(0, 102, 102));
        btnRemove.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Remove");
        btnRemove.setPreferredSize(new java.awt.Dimension(72, 25));

        btnExport.setBackground(new java.awt.Color(0, 102, 102));
        btnExport.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(255, 255, 255));
        btnExport.setText("Export");

        btnAdd.setBackground(new java.awt.Color(0, 102, 102));
        btnAdd.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");

        btnEdit.setBackground(new java.awt.Color(0, 102, 102));
        btnEdit.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");

        lbSum.setBackground(new java.awt.Color(0, 153, 153));
        lbSum.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        lbSum.setForeground(new java.awt.Color(255, 255, 255));
        lbSum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSum.setText("Sum");
        lbSum.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lbSum.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbSum.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbSum.setOpaque(true);

        lbSumShow.setBackground(new java.awt.Color(255, 255, 255));
        lbSumShow.setForeground(new java.awt.Color(0, 0, 0));
        lbSumShow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lbSumShow.setOpaque(true);

        pAdd.setBackground(new java.awt.Color(0, 153, 153));
        pAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pAdd.setForeground(new java.awt.Color(153, 255, 255));
        pAdd.setToolTipText("");

        tfNameShow.setBackground(new java.awt.Color(255, 255, 255));
        tfNameShow.setForeground(new java.awt.Color(0, 102, 102));
        tfNameShow.setEnabled(false);
        tfNameShow.setOpaque(true);

        tfPriceShow.setBackground(new java.awt.Color(255, 255, 255));
        tfPriceShow.setForeground(new java.awt.Color(0, 102, 102));
        tfPriceShow.setEnabled(false);
        tfPriceShow.setOpaque(true);
        tfPriceShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPriceShowActionPerformed(evt);
            }
        });

        tfQuantityShow.setBackground(new java.awt.Color(255, 255, 255));
        tfQuantityShow.setForeground(new java.awt.Color(0, 102, 102));
        tfQuantityShow.setOpaque(true);

        taDescription.setBackground(new java.awt.Color(255, 255, 255));
        taDescription.setColumns(20);
        taDescription.setForeground(new java.awt.Color(0, 102, 102));
        taDescription.setRows(5);
        taDescription.setEnabled(false);
        scpOfDescription.setViewportView(taDescription);

        btnSave.setBackground(new java.awt.Color(0, 102, 102));
        btnSave.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lbName.setBackground(new java.awt.Color(255, 255, 255));
        lbName.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(0, 102, 102));
        lbName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbName.setText("Name");
        lbName.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbName.setOpaque(true);

        lbPrice.setBackground(new java.awt.Color(255, 255, 255));
        lbPrice.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        lbPrice.setForeground(new java.awt.Color(0, 102, 102));
        lbPrice.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbPrice.setText("Price");
        lbPrice.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbPrice.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbPrice.setOpaque(true);

        lbDescription.setBackground(new java.awt.Color(255, 255, 255));
        lbDescription.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        lbDescription.setForeground(new java.awt.Color(0, 102, 102));
        lbDescription.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDescription.setText("Description");
        lbDescription.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbDescription.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbDescription.setOpaque(true);

        lbQuantity.setBackground(new java.awt.Color(255, 255, 255));
        lbQuantity.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        lbQuantity.setForeground(new java.awt.Color(0, 102, 102));
        lbQuantity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbQuantity.setText("Quantity");
        lbQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        lbQuantity.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lbQuantity.setOpaque(true);

        javax.swing.GroupLayout pAddLayout = new javax.swing.GroupLayout(pAdd);
        pAdd.setLayout(pAddLayout);
        pAddLayout.setHorizontalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescription, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                    .addComponent(lbQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbPrice, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfPriceShow, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tfNameShow, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scpOfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pAddLayout.createSequentialGroup()
                            .addComponent(tfQuantityShow, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pAddLayout.setVerticalGroup(
            pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNameShow)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfPriceShow)
                    .addComponent(lbPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scpOfDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfQuantityShow, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        table.setBackground(new java.awt.Color(0, 153, 153));
        table.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stt", "Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setSelectionBackground(new java.awt.Color(204, 255, 255));
        scpOfTable.setViewportView(table);

        tfFindDish.setBackground(new java.awt.Color(255, 255, 255));
        tfFindDish.setForeground(new java.awt.Color(0, 102, 102));

        btnFindDish.setBackground(new java.awt.Color(0, 102, 102));
        btnFindDish.setFont(new java.awt.Font("SVN-Amsi Narw Light", 1, 14)); // NOI18N
        btnFindDish.setForeground(new java.awt.Color(255, 255, 255));
        btnFindDish.setText("Find by name");

        scpRcm.setBackground(new java.awt.Color(255, 255, 255));

        pRcmDish.setBackground(new java.awt.Color(255, 255, 255));
        pRcmDish.setLayout(new java.awt.GridLayout(5, 0));
        scpRcm.setViewportView(pRcmDish);

        javax.swing.GroupLayout pTableInfoLayout = new javax.swing.GroupLayout(pTableInfo);
        pTableInfo.setLayout(pTableInfoLayout);
        pTableInfoLayout.setHorizontalGroup(
            pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTableInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(scpOfTable)
                    .addGroup(pTableInfoLayout.createSequentialGroup()
                        .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pTableInfoLayout.createSequentialGroup()
                                .addComponent(tfFindDish, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFindDish, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(scpRcm, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pTableInfoLayout.createSequentialGroup()
                                    .addGap(41, 41, 41)
                                    .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(27, 27, 27)
                                    .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnExport, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pTableInfoLayout.createSequentialGroup()
                                .addComponent(lbSum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbSumShow, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(pAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pTableInfoLayout.setVerticalGroup(
            pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTableInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scpOfTable, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTableInfoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfFindDish, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFindDish, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(scpRcm, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnExport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6))
                    .addGroup(pTableInfoLayout.createSequentialGroup()
                        .addGroup(pTableInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbSum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbSumShow, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(pAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTableInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pTableInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tfPriceShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPriceShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPriceShowActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnEdit;
    public javax.swing.JButton btnExport;
    public javax.swing.JButton btnFindDish;
    public javax.swing.JButton btnRemove;
    public javax.swing.JButton btnSave;
    public javax.swing.JLabel lbDescription;
    public javax.swing.JLabel lbName;
    public javax.swing.JLabel lbPrice;
    public javax.swing.JLabel lbQuantity;
    private javax.swing.JLabel lbSum;
    public javax.swing.JLabel lbSumShow;
    public javax.swing.JPanel pAdd;
    public javax.swing.JPanel pRcmDish;
    public javax.swing.JPanel pTableInfo;
    private javax.swing.JScrollPane scpOfDescription;
    private javax.swing.JScrollPane scpOfTable;
    public javax.swing.JScrollPane scpRcm;
    public javax.swing.JTextArea taDescription;
    public javax.swing.JTable table;
    public javax.swing.JTextField tfFindDish;
    public javax.swing.JTextField tfNameShow;
    public javax.swing.JTextField tfPriceShow;
    public javax.swing.JTextField tfQuantityShow;
    // End of variables declaration//GEN-END:variables
}
